### ISSUE TITLE
fresh install will not compile basic

### ISSUE THREAD

**Issue by kaosbeat** [Dotneteer/kliveide#210]
When installing Klive as per instructions (v0.8.0) I can compile and run the code.z80asm example, it opens nice in klive shouting "Hello from KLive IDE, (z80 Assembler)", but not the program.bor
The Klive Compiler gives me the following output:

```
Compiling /code/program.bor
Executing zxbc /code/program.bor --output /.generated/program.bor.z80asm --asm --optimize 2 --org 32768 --heap-size 4096

Invoking the Klive Z80 Assembler
Compilation failed.
Z0004: '(' expected (/code/program.bor:1)
Z0004: '(' expected (/code/program.bor:2)
Z0004: '(' expected (/code/program.bor:3)
Compilation time: 10 ms
```

no z80asm file is written to .generated though. If I change the zxbc path to a faulty one, the compiler complains that zxbc cannot be found. If I manually run the command from a terminal, the corresponding file is generated, but it will not load using the assembler injector.

If I inspect the manually generated file I fined 5 syntax problems
```
Z0605: Identifier '__SET_ATTR2' is not defined yet.
Z0605: Identifier 'INVERSE_TMP' is not defined yet.
Z0605: Identifier 'OVER_TMP' is not defined yet.
Z0605: Identifier 'BOLD_TMP' is not defined yet.
Z0605: Identifier 'ITALIC_TMP' is not defined yet.
```
spread out over the 1692 lines of generated code...

I've  set the program target to zx 48k but have got no clue of what is going on. Am I missing a part?

**Comment by kaosbeat** [comment]
when compiling the program.bor using `zxbc -taB /code/program.bor`  I can run the output .tap file in the emulator

**Comment by Dotneteer** [comment]
@kaosbeat, thanks for signing this issue! Please send me the ZXBC version you use together with Klive so that I can try the same.

Today I'm on a workshop but try to look after this issue as soon as I can.

**Comment by kaosbeat** [comment]
zxbc.py 1.14.0 (latest stable)
klive v0.8.0 (installed from vsix)

**Comment by Dotneteer** [comment]
@kaosbeat, it seems strange. I'm using Windows, at here the core compiles and runs successfully. Please, check another thing! Look at the generated `/.generated/program.bor.z80asm` file, and send me its first 10 lines, please.

**Comment by kaosbeat** [comment]
It seems like the `/.generated/program.bor.z80asm` is not passed into the the assembler but the `/code/program.bor` file itself is. If I change it the assembler output errors follow along.

```
rem Sample code
1234 print at 10,5; bright 1; ink 1; "Hello, from Klive IDE!"
5678 print at 11,5; bright 1; ink 2; "   (Boriel's Basic)   "
```
 gives the following error  (explicitely mentioning program.bor as well)

```
Invoking the Klive Z80 Assembler
Compilation failed.
Z0004: '(' expected (/code/program.bor:1)
Z0002: A line cannot start with this token: 1234 (/code/program.bor:2)
Z0002: A line cannot start with this token: 5678 (/code/program.bor:3)
Compilation time: 13 ms
```

If I manually generate a file the first 10 lines are as follows:
```
	org 32768
__START_PROGRAM:
	di
	push ix
	push iy
	exx
	push hl
	exx
	ld hl, 0
	add hl, sp
```

but like I said, I still cannot assemble this, while the demo code.z80asm will assemble and be injected successfully

**Comment by Dotneteer** [comment]
When you run a Boriel's Basic file, Klive uses two compilation steps. First, it invokes the ZXBC command that creates a .z80asm file (`/.generated/program.bor.z80asm`), in this case. Next Klive attaches the `.zxbasic` pragma to the top of the generated file, and than invokes the Z80 Assembler. If you manually add the `.zxbasic` pragma to the top of the generated asm file, compilation should work. Your file should look like this before compilation:

```
        .zxbasic
	org 32768
__START_PROGRAM:
	di
	push ix
	push iy
	exx
	push hl
	; ...
```

The `.zxbasic` tells the Z80 Assembler that is should use the "Boriel's Basic" dialect of the assembler. Without it, the code won't compile.

It seems so that the ZXBC utility did not run on your machine (surprisingly, did not raise any error, and this is maybe a Klive bug). If ZXBC runs, an output like "ZXBC execution time" would be displayed in the output, but that is missing. Please, check again that you have specified the full path to the ZXBC utility in Klive settings within VS Code!

**Comment by Dotneteer** [comment]
@kaosbeat, I've just checked, and there's a bug in Klive: if your ZXBC utility does not run, because you have specified a wrong path, it does not display an error message. So, I'm almost sure that the ZXBC path setting is the issue in your case. Please, provide an **absolute** path to access the ZXBC utility!

Nonetheless, I added to bug to my backlog. When my workshop is over, I fix this bug and send you a private build.

**Comment by kaosbeat** [comment]
![Screen Shot 2021-01-14 at 14 02 57](https://user-images.githubusercontent.com/204628/104594450-72aa7900-5671-11eb-86dc-abaf7a9540e3.png)

If I open a terminal and copy the path, zxbc runs, so I'm using an absolute path.
there is a path problem somewhere though...
I started fiddling with the settings and now I get the path error ( reloaded, restarted, uninstalled, reinstalled, tried a different version, ...)

`/bin/sh: zxbc: command not found`

the path is still correct though

I then added a symbolic link to /usr/local/bin so zxbc is in my path. I now get a different error

`/usr/local/bin/zxbc: line 8: /usr/local/bin/python/bin/python: No such file or directory`

**Comment by kaosbeat** [comment]
FIXED!

I added an 
export PATH="/usr/local/opt/zxbasic:$PATH"

to my ~/.bash_profile

and now everything works!
