### ISSUE TITLE
[Linux] Can't create new project

### ISSUE THREAD

**Issue by axredneck** [Dotneteer/kliveide#624]
![Screenshot_20231116_164915](https://github.com/Dotneteer/kliveide/assets/20617900/4a405e6a-d74b-40e7-876f-c68934b62c6c)
Klive IDE 0.30.0 Appimage, Arch Linux.

**Comment by Dotneteer** [comment]
Hi @axredneck, you're quick to download the new Klive IDE version. This version is just a deployment test version so that I can write the documentation, it is not officially released. Nonetheless, I'm happy you tried it, and especially for you agility to use Linux.

In about two weeks, I release an official (and so supported) version of Klive.

Thanks again for signing me this issue, and stay tuned!

**Comment by axredneck** [comment]
Now (Klive IDE 0.30.2) it's even worse:
![Screenshot_20231127_000720](https://github.com/Dotneteer/kliveide/assets/20617900/0f07d829-a333-4580-843a-6e21bb3643d0)

**Comment by Dotneteer** [comment]
@axredneck, thanks again!

This issue was an unremoved log message. I removed it, and now the new release is available: 
https://github.com/Dotneteer/kliveide/releases/tag/v0.30.3

Please keep reporting bugs and other issues!

**One more thing**: As I'm not a Linux guru, I count on the community to help me with Linux issues. Could you help me describe the Linux installation steps (see the documentation here: https://dotneteer.github.io/kliveide/getting-started/installation#linux-installation)

**Comment by axredneck** [comment]
> Could you help me describe the Linux installation steps
Download Klive IDE appimage, mark it as executable, then run it, that's all.
