### ISSUE TITLE
Problem with non-clicable file that doesn't open in editor

### ISSUE THREAD

**Issue by mickpr** [Dotneteer/kliveide#770]
Still there are problem with non-clicable file that doesn't open in editor. Project path doesn't contain spaces. File opens when you do "project compile", and there is shown a link to a file at bottom IDE panel - that can by clicked, and then the file opens properly.  
Could you check it? I've a Python 3.11 installed before - if it has a meaning.  I've tested it on several machines, and the problem exist on all of these.  Thanks for your answer. 
I used Window's latest version of Your project, and it happens also in previous version.

**Comment by Dotneteer** [comment]
@mickpr, I've just tried the latest version on Windows with a newly created Klive project (ZX Spectrum 48K, using the "default" template); it worked without issues.

Please, in an email (dotneteer@hotmail.com), send me the zipped version of the project folder (including all files), and also write me the root folder name of the project (like "C:\Users\joe\MyProjects\ThisProject")  so that I can understand the entire context you work in. Unless I reproduce the issue, I do not know what to fix.

Also, please send me some tech specs about the machine you're using Windows on.

**Comment by Dotneteer** [comment]
@mickpr, As I did not manage to reproduce this issue, I closed it. Feel free to reopen it when you can provide me with some helper info (see the last comment before this one)!
